// GENERATED by a one-off port of the owner-approved prototype v2 (apm-experience-prototype.html,
// its DATA object), then restructured per the owner decisions of 7 Oct 2026 (docs/34 §14):
// "Mind & learning" split into Mind and Spirit ("What feeds your spirit?"), the bed question made
// essential (asked of everyone), the three pillars as defaults. Edit this file, not the prototype.
import type { AreaKey } from '@apm/domain';
import type { GameKey, GoalTemplate, IntakeAnswers, SectionDef } from './types.js';

/** Bump when a question id or option id changes; add the rename to OPTION_MIGRATIONS. */
export const BANK_VERSION = 2;

const arr = (a: IntakeAnswers, id: string): string[] => (Array.isArray(a[id]) ? (a[id] as string[]) : []);

export const GAMES: ReadonlyArray<readonly [GameKey, string]> = [
  ['wealth', 'Building wealth'],
  ['weight', 'Losing weight / getting healthy'],
  ['founder', 'Founder / entrepreneur'],
  ['operator', 'Operator: moving up at a company'],
  ['parent', 'Parent / caregiver'],
  ['athlete', 'Athlete / training'],
  ['student', 'Student / studying'],
  ['creator', 'Creator / making things'],
  ['transition', 'Going through a life transition'],
];

export const GOAL_TEMPLATES: Readonly<Record<GameKey, readonly GoalTemplate[]>> = {
  weight: [
    { id: 'lose_weight', label: 'Lose weight', size: { min: 5, max: 100, step: 5, unit: 'lb', def: 20, question: 'How much would you like to lose?' }, steps: ['Walk 10 minutes today', 'Put workout clothes out tonight', 'Log what I eat today', 'Book a check-up'] },
    { id: 'workout_habit', label: 'Build a steady workout habit', size: { min: 1, max: 6, step: 1, unit: 'sessions / week', def: 3, question: 'How many sessions a week is the target?' }, steps: ['Schedule this week\'s 3 sessions', 'Do one 20-minute session today', 'Pick the gym or video I will use'] },
    { id: 'eat_better', label: 'Eat better most days', steps: ['Plan tomorrow\'s lunch tonight', 'Drink a glass of water with every meal', 'Shop with a list this week'] },
    { id: 'energy', label: 'Get my energy back', steps: ['Walk 10 minutes in daylight today', 'Set a fixed bedtime tonight', 'Drink water before coffee tomorrow'] },
  ],
  wealth: [
    { id: 'emergency_fund', label: 'Build an emergency fund', size: { min: 1, max: 6, step: 1, unit: 'months of expenses', def: 3, question: 'How many months of expenses should it cover?' }, steps: ['Open a separate savings account', 'Set an automatic transfer for payday', 'Write down my monthly essentials'] },
    { id: 'pay_debt', label: 'Pay off debt', size: { min: 1, max: 10, step: 1, unit: 'debts', def: 3, question: 'How many separate debts do you have?' }, steps: ['List every debt with balance and rate', 'Pick the one debt to attack first', 'Set the minimum payments to automatic'] },
    { id: 'invest_monthly', label: 'Start investing every month', steps: ['Choose the day each month I invest', 'Set an automatic monthly transfer', 'Write my rule for what I never sell in a panic'] },
    { id: 'save_goal', label: 'Save for a big goal', size: { min: 1, max: 100, step: 1, unit: 'thousand USD', def: 10, question: 'Roughly how much are you saving toward?' }, steps: ['Open a savings account just for this goal', 'Cancel one unused subscription', 'Set an automatic transfer for payday'] },
  ],
  founder: [
    { id: 'launch', label: 'Launch a product', steps: ['Write the launch checklist', 'Book the launch date on my calendar', 'Send the beta invite to 5 people'] },
    { id: 'customers', label: 'Get paying customers', size: { min: 1, max: 100, step: 1, unit: 'paying customers', def: 10, question: 'How many paying customers by the target date?' }, steps: ['Send 5 customer outreach messages', 'Book 3 customer calls', 'Write the one-line offer'] },
    { id: 'revenue', label: 'Hit a revenue target', size: { min: 1, max: 500, step: 1, unit: 'thousand USD / month', def: 20, question: 'What monthly revenue are you aiming for?' }, steps: ['List the top 10 deals in play', 'Send 3 follow-ups on open proposals', 'Write this month\'s revenue plan'] },
    { id: 'raise', label: 'Raise money', steps: ['Draft the investor update', 'List 20 target investors', 'Ask one founder for an intro'] },
    { id: 'hire', label: 'Hire my next person', steps: ['Write the role in one paragraph', 'Post the role in one place', 'Message 3 people for referrals'] },
  ],
  operator: [
    { id: 'promotion', label: 'Get promoted', steps: ['Ask my manager what the next level requires', 'Write my 90-day results list', 'Book a 1:1 with my skip-level'] },
    { id: 'visible_project', label: 'Ship a high-visibility project', steps: ['Write a one-page project plan', 'Book the kickoff meeting', 'Name the first milestone and date'] },
    { id: 'lead_team', label: 'Lead my team better', steps: ['Book a 1:1 with each report', 'Write the team\'s top 3 priorities', 'Ask the team one question about blockers'] },
    { id: 'new_role', label: 'Move to a new role or company', steps: ['Update my resume headline', 'Message 3 people in roles I want', 'List 10 target companies'] },
  ],
  parent: [
    { id: 'calm_mornings', label: 'Calmer school mornings', steps: ['Pack bags the night before', 'Set out clothes tonight', 'Write the 5-step morning checklist'] },
    { id: 'present_time', label: 'More present time with my kids', steps: ['Put my phone in another room at dinner', 'Book one kid-only outing this week', 'Protect bedtime for 20 minutes tonight'] },
    { id: 'household', label: 'Get the household organised', steps: ['Write this week\'s family schedule', 'Do a 10-minute tidy tonight', 'List the forms and payments due this month'] },
    { id: 'newborn', label: 'Stabilise a newborn routine', steps: ['Write the feed and sleep handoff plan', 'Ask for one specific help slot this week', 'Prep tomorrow\'s bottles or bag tonight'] },
  ],
  athlete: [
    { id: 'race', label: 'Train for a race or event', steps: ['Schedule this week\'s sessions', 'Do a 20-minute easy session today', 'Write the event date on my calendar'] },
    { id: 'stronger', label: 'Get stronger', steps: ['Book 3 strength sessions this week', 'Record today\'s starting lifts', 'Prep my gym bag tonight'] },
    { id: 'return_injury', label: 'Return from injury safely', steps: ['Book a physio check', 'Do today\'s prescribed rehab', 'Write my pain-stop rule'] },
    { id: 'qualify', label: 'Make the team or qualify', steps: ['Write the qualifying standard', 'Schedule this week\'s key session', 'Ask my coach for one focus'] },
  ],
  student: [
    { id: 'exam', label: 'Pass a big exam', steps: ['List every topic on the exam', 'Book 3 study blocks this week', 'Do one past paper question today'] },
    { id: 'grades', label: 'Raise my grades', steps: ['List assignments due this month', 'Book one office-hours slot', 'Do 25 minutes on the hardest subject today'] },
    { id: 'thesis', label: 'Finish a thesis or project', steps: ['Write the chapter outline', 'Write 200 words today', 'Book a check-in with my advisor'] },
    { id: 'admission', label: 'Get into a program', steps: ['List the deadlines and requirements', 'Draft the first paragraph of my statement', 'Ask one person for a reference'] },
  ],
  creator: [
    { id: 'ship_release', label: 'Ship a release or publication', steps: ['Write the release checklist', 'Finish one section today', 'Set the release date'] },
    { id: 'consistent', label: 'Post consistently', size: { min: 1, max: 14, step: 1, unit: 'posts / week', def: 3, question: 'How many posts a week?' }, steps: ['Batch 3 post ideas today', 'Schedule this week\'s posting slots', 'Finish and post one piece today'] },
    { id: 'draft', label: 'Finish a draft', steps: ['Write 300 words today', 'Outline the remaining sections', 'Book 3 writing blocks this week'] },
    { id: 'audience', label: 'Grow an audience', steps: ['Reply to 5 comments today', 'Write my one-line positioning', 'Pitch one collaboration'] },
  ],
  transition: [
    { id: 'new_job', label: 'Land a new job', steps: ['Update my resume headline', 'Apply to 3 roles', 'Message 2 people for coffee chats'] },
    { id: 'move', label: 'Settle into a move', steps: ['List the address changes to make', 'Unpack one room today', 'Find the nearest essentials'] },
    { id: 'rebuild', label: 'Rebuild after a loss or breakup', steps: ['Walk 10 minutes outside today', 'Text one friend', 'Write tomorrow\'s 3 basics'] },
    { id: 'stabilise_money', label: 'Stabilise my finances after a change', steps: ['List this month\'s essential bills', 'Set one automatic payment', 'Cancel one unused subscription'] },
  ],
};

/** Minimum-floor chips per game (≤ 15 min, MVD_MAX_MINUTES), each mapped to its area. */
export const FLOOR_CHIPS: Readonly<Record<GameKey | '_all', ReadonlyArray<{ label: string; area: AreaKey }>>> = {
  weight: [{ label: 'Walk 10 minutes', area: 'movement' }, { label: 'Drink water and stretch 2 minutes', area: 'food' }, { label: 'Log one meal', area: 'food' }],
  athlete: [{ label: '10-minute mobility or recovery walk', area: 'movement' }, { label: 'Prep tomorrow\'s session kit', area: 'movement' }],
  wealth: [{ label: 'Check my balance for 5 minutes', area: 'money' }, { label: 'Move any amount to savings', area: 'money' }, { label: 'Pay one bill on time', area: 'money' }],
  founder: [{ label: 'Send one decisive follow-up', area: 'work' }, { label: 'Do 15 minutes on the foreground task', area: 'work' }],
  operator: [{ label: 'Finish one concrete deliverable step', area: 'work' }, { label: 'Reply to the one message that matters', area: 'work' }],
  parent: [{ label: 'One protected family touchpoint (20 min, phone away)', area: 'family' }, { label: 'Prep tomorrow\'s bags', area: 'family' }],
  student: [{ label: '15-minute review of the next tested topic', area: 'work' }],
  creator: [{ label: 'Open the file and finish one defined section', area: 'work' }],
  transition: [{ label: 'One stabilising admin task', area: 'work' }],
  _all: [{ label: 'Read one page', area: 'learning' }, { label: '3 slow breaths and a glass of water', area: 'meditation' }, { label: 'Write tomorrow\'s first step', area: 'work' }],
};

export const SECTIONS: readonly SectionDef[] = [
  {
    id: 's1', kind: 'questions', name: 'Your game', intro: 'Tap everything that applies. One life, many games.',
    after: { id: 'i1', kind: 'heard', title: 'Here\'s what we heard', plate: 'From now on APM holds this list. You don\'t have to.' },
    questions: [
      { id: 'games', type: 'multi', title: 'Which games are you playing right now?', options: [['wealth', 'Building wealth'], ['weight', 'Losing weight / getting healthy'], ['founder', 'Founder / entrepreneur'], ['operator', 'Operator: moving up at a company'], ['parent', 'Parent / caregiver'], ['athlete', 'Athlete / training'], ['student', 'Student / studying'], ['creator', 'Creator / making things'], ['transition', 'Going through a life transition']], minPick: 1, why: 'Persona detection; one person can be a parent, founder and athlete at once.', bhpc: 'A: identity + context; App persona map (docs/32)', field: 'roles[]', engine: 'recognizePersona, recommendTrackKeys', plate: 'You stop explaining your life to a planner. APM fits the plan to all of it.' },
      { id: 'foreground', type: 'single', title: 'Which one needs the most push for the next 90 days?', note: 'The others stay protected and maintained. Nothing gets dropped.', options: 'fromGames', gate: (a) => arr(a, 'games').length > 1, why: 'Exactly one Foreground; the rest is maintenance.', bhpc: 'VII Foreground priority + Arbitration', field: 'foregroundPersona', engine: 'arbitrateForeground, generateGoalPlan', plate: 'You stop splitting your energy evenly across everything.' },
      { id: 'season', type: 'single', title: 'What season are you in?', options: [['building', 'Building'], ['maintaining', 'Maintaining'], ['launching', 'Launching / competing'], ['recovering', 'Recovering'], ['rebuilding', 'Rebuilding'], ['transitioning', 'Transitioning']], why: 'Sets intensity. A recovering season starts lighter.', bhpc: 'A: context; VIII Modes', field: 'currentSeason', engine: 'resolveRuntimeMode (initial mode)', plate: 'APM sets the pace so you don\'t have to judge it each morning.' },
      { id: 'load', type: 'slider', title: 'How full does your head feel right now?', min: 1, max: 10, step: 1, def: 7, lo: 'Clear', hi: 'Completely full', why: 'Baseline for the promise. Asked again on Day 5 and Day 7.', bhpc: 'I: zero cognitive load; XIII Day 5 "Lower mental load"', field: 'loadBaseline (NEW)', engine: 'first-week review (stabilizationDay)', plate: 'We measure the load so you can watch it drop.' },
      { id: 'carry', type: 'multi', title: 'What are you carrying in your head right now?', options: [['deadlines', 'Deadlines'], ['money', 'Money worries'], ['family_logistics', 'Family logistics'], ['health', 'Health goals'], ['replies', 'Messages I owe'], ['big_decision', 'A big decision'], ['too_many', 'Too many projects'], ['restarting', 'Restarting (again)'], ['appointments', 'Appointments and forms'], ['bills', 'Bills and renewals']], minPick: 1, why: 'The "dump all my stuff" list. Seeds Radar and the reveal.', bhpc: 'I: decision fatigue; Radar seeding', field: 'mentalLoadItems[] (NEW)', engine: 'Radar seed + reveal copy', plate: 'Everything you tap here moves from your head into APM.' },
    ],
  },
  {
    id: 's2', kind: 'questions', name: 'Your goal', intro: 'Pick the closest. You can tweak it at the end.',
    after: { id: 'i2', kind: 'plan', title: 'Your 90 days, already sequenced', plate: 'Taken off your plate: figuring out how to get there.' },
    questions: [
      { id: 'goal', type: 'single', title: 'What do you want to make happen first?', options: 'goalTemplates', why: 'The 90-day Foreground project. Templates replace a blank text box.', bhpc: 'B: primary outcome; C: goals into Tracks; Prompt #1 30-day Foreground Project', field: 'primaryGoal, foregroundProjectName', engine: 'generateGoalPlan(goalText)', plate: 'You don\'t have to word the goal. Pick it; APM writes the plan.' },
      { id: 'goal_size', type: 'slider', title: 'goalSize', gate: (a, h) => h.goalHasSize(a), why: 'Makes the outcome measurable; drives the safe-pace check.', bhpc: 'B: success criteria', field: 'goalOutcome', engine: 'generateGoalPlan (safe pace, milestones)', plate: 'APM turns the number into weekly steps.' },
      { id: 'target', type: 'single', title: 'By when?', options: [['30', '30 days'], ['60', '60 days'], ['90', '90 days'], ['180', '6 months'], ['365', '1 year'], ['none', 'No hard date']], recommended: () => '90', why: 'Timeline and gates.', bhpc: 'B: timelines + deadlines; VII 30/60/90', field: 'goalTargetDate, reviewGateDays', engine: 'generateGoalPlan(targetDate)', plate: 'APM sets the checkpoints, so you never ask "am I on track?"' },
      { id: 'first_step', type: 'single', title: 'Which first step could you do this week?', options: 'goalSteps', why: 'A physical next action, never "work on X".', bhpc: 'VI Clarity guarantee (ambiguity stop)', field: 'firstNextAction', engine: 'isExecutableActionTitle, plan day 1', plate: 'The first move is already decided.' },
      { id: 'deadlines', type: 'multi', title: 'Any hard deadlines in the next 90 days?', options: [['none', 'None'], ['exam', 'Exam'], ['launch', 'Launch'], ['race', 'Race / competition'], ['event', 'Event / wedding'], ['tax', 'Tax or filing'], ['baby', 'Baby due'], ['review', 'Performance review'], ['move', 'Move']], minPick: 1, exclusive: 'none', why: 'Real external urgency for arbitration and Radar.', bhpc: 'B: hard deadlines; VII Urgency', field: 'deadlines[] (NEW)', engine: 'arbitrateForeground (urgency), Radar', plate: 'APM watches the dates and warns you early.' },
      { id: 'deadline_when', type: 'single', title: 'When is the nearest one?', options: [['week', 'This week'], ['month', 'This month'], ['quarter', 'In 1 to 3 months']], gate: (a) => arr(a, 'deadlines').length > 0 && !arr(a, 'deadlines').includes('none'), why: 'Urgency score.', bhpc: 'VII Urgency', field: 'deadlines[].window (NEW)', engine: 'arbitrateForeground', plate: 'You won\'t need to count the days. APM does.' },
    ],
  },
  { id: 'acct', kind: 'account', name: 'Save your plan', questions: [] },
  {
    id: 's3', kind: 'questions', name: 'Your time', intro: 'So APM plans around your real day.',
    questions: [
      { id: 'wake', type: 'time', title: 'What time do you want to wake up?', min: 270, max: 600, step: 15, def: 390, why: 'Morning trigger time.', bhpc: 'A: wake target; Step 5D automate the trigger', field: 'wakeTime (NEW)', engine: 'push schedule for the morning agenda', plate: 'Your agenda will be waiting. You never have to ask for it.' },
      { id: 'sleep', type: 'time', title: 'What time do you want to be asleep?', min: 1200, max: 1500, step: 15, def: 1350, why: 'Evening close time; sleep rule.', bhpc: 'A: sleep target; F: sleep rules', field: 'sleepTime (NEW)', engine: 'end-of-day prompt time, boundary checks', plate: 'APM protects your sleep from late plans.' },
      { id: 'fixed', type: 'multi', title: 'What is fixed in your day?', options: [['school_run', 'School run / pickup'], ['commute', 'Commute'], ['work_hours', 'Set work hours'], ['caregiving', 'Caregiving shift'], ['training', 'Training session'], ['classes', 'Classes'], ['worship', 'Worship'], ['none', 'Nothing fixed']], minPick: 1, exclusive: 'none', why: 'Fixed commitments the plan must route around.', bhpc: 'A: fixed daily commitments', field: 'fixedCommitments[] (NEW)', engine: 'buildDailyPlan (blocked time)', plate: 'APM plans around these, so you never double-book yourself.' },
      { id: 'travel', type: 'single', title: 'How often do you travel?', options: [['rarely', 'Rarely'], ['monthly', 'About monthly'], ['weekly', 'Most weeks'], ['constantly', 'Constantly']], why: 'Travel days run lighter.', bhpc: 'A: travel patterns', field: 'travelPattern (NEW)', engine: 'availability.restDays on travel days', plate: 'Travel days shrink automatically. No guilt.' },
      { id: 'minutes', type: 'slider', title: 'On a normal day, how many minutes can your #1 goal get?', min: 10, max: 240, step: 5, def: 45, unit: 'min', why: 'Caps daily actions to real time.', bhpc: 'Prompt #3 constraints: hours available', field: 'availability.defaultMinutes', engine: 'generateGoalPlan (capMinutes)', plate: 'APM never hands you more than fits.' },
    ],
  },
  {
    id: 's4', kind: 'questions', name: 'What knocks you off course', intro: 'No judgement. This is how APM catches you.',
    after: { id: 'i3', kind: 'laws', title: 'It\'s a continuity problem, not a discipline problem', plate: 'Taken off your plate: deciding what to do after a bad day.' },
    questions: [
      { id: 'patterns', type: 'multi', title: 'Which of these sound like you?', options: [['perfectionism', 'Perfectionism'], ['avoidance', 'Avoidance / procrastination'], ['all_or_nothing', 'All-or-nothing'], ['shame', 'Shame spiral after a miss'], ['crash', 'Energy crashes'], ['burnout', 'Burnout'], ['overcommit', 'Overcommitting'], ['quit_after_miss', 'Quitting after a miss'], ['new_system', 'Rebuilding my system again'], ['pivot', 'Pivoting too early'], ['renegotiate', 'Changing the plan mid-day'], ['scroll', 'Phone / scrolling']], optional: true, why: 'Drives Track recommendations and coaching focus.', bhpc: 'E: failure modes, perfectionism, avoidance, shame, energy crash', field: 'failurePatterns[]', engine: 'recommendTrackKeys(failurePatterns)', plate: 'APM watches for these so you don\'t have to police yourself.' },
      { id: 'after_miss', type: 'single', title: 'When you miss a day, what usually happens next?', options: [['bounce', 'I bounce back the next day'], ['two_three', 'I lose 2 or 3 days'], ['week', 'I lose a week or more'], ['quit', 'I usually quit']], why: 'How hard Never Miss Twice and Recovery must work.', bhpc: 'II Law 1 Never Miss Twice; VI Continuity guarantee', field: 'missPattern (NEW)', engine: 'shouldForceRecovery, resilience Track', plate: 'After a miss, APM shrinks the next day for you. No catch-up.' },
      { id: 'energy', type: 'single', title: 'When is your energy lowest?', options: [['morning', 'Morning'], ['afternoon', 'Early afternoon'], ['evening', 'Evening'], ['unpredictable', 'Unpredictable']], why: 'Hard work goes where energy is.', bhpc: 'E: energy crash patterns; VII Energy match', field: 'energyDip (NEW)', engine: 'buildDailyPlan ordering', plate: 'Hard tasks land when you\'re strongest. APM does the sorting.' },
    ],
  },
  { id: 'express', kind: 'express', name: 'Quick start or full setup', questions: [] },
  {
    id: 's5', kind: 'questions', name: 'Body', intro: 'Behaviour only. APM never gives diet or medical advice.',
    questions: [
      { id: 'core_pillars', type: 'multi', title: 'APM looks after your Mind, Body and Spirit by default. Keep all three?', note: 'Mind holds work, money, learning and focus. Body holds movement, food and sleep. Spirit holds faith, stillness and family. Untick one to switch it off.', options: [['mind', 'Mind'], ['body', 'Body'], ['spirit', 'Spirit']], optional: true, prefill: 'core', why: 'Owner default (7 Oct 2026): every OS starts with Mind, Body and Spirit pillars unless the user steers away.', bhpc: 'F/H: body + spirit pillars; owner default', field: 'pillars.mind/body/spirit enabled', engine: 'pillar proposal', plate: 'The basics are covered without you deciding to cover them.' },
      { id: 'move', type: 'multi', title: 'What movement would you actually do?', options: [['walk', 'Walking'], ['gym', 'Gym'], ['home', 'Home workouts / YouTube'], ['trainer', 'Trainer'], ['run', 'Running'], ['sport', 'A sport'], ['yoga', 'Yoga / Pilates'], ['none_yet', 'Nothing yet']], minPick: 1, exclusive: 'none_yet', gate: (a, h) => h.bodyOn(a), why: 'Plan uses what you will really do.', bhpc: 'F: movement options; N3: trainer or YouTube?', field: 'bodyContext.movement[]', engine: 'generateGoalPlan (body actions)', plate: 'APM picks the workout; you just show up.' },
      { id: 'workout_days', type: 'slider', title: 'How many days a week can you move?', min: 0, max: 7, step: 1, def: 3, unit: 'days', gate: (a, h) => h.bodyOn(a), why: 'Heavy vs rest days for the body pillar.', bhpc: 'N3: heavy lifting vs rest days', field: 'bodyContext.daysPerWeek', engine: 'generateGoalPlan cadence', plate: 'Rest days are planned too, so they never feel like failure.' },
      { id: 'food', type: 'multi', title: 'Which of these happen a lot?', note: 'No judgement. APM picks one small habit to start with.', options: [['skip_breakfast', 'I skip breakfast'], ['late_eating', 'Late-night eating'], ['takeout', 'A lot of takeout'], ['water', 'I don\'t drink enough water'], ['fine', 'Mostly fine']], minPick: 1, exclusive: 'fine', gate: (a, h) => h.bodyOn(a), why: 'Small behaviour targets, not a diet.', bhpc: 'F: diet + hydration', field: 'bodyContext.food[]', engine: 'body_foundation Track rules', plate: 'One small food habit at a time. APM picks which.' },
      { id: 'weight_now', type: 'slider', title: 'What is your current weight?', note: 'Optional. Only used to keep the pace safe. Never shown on Today, never shared.', min: 90, max: 400, step: 1, def: 180, unit: 'lb', optional: true, gate: (a, h) => h.any(a, 'weight') && a.goal === 'lose_weight', why: 'Safe-pace ceiling.', bhpc: 'App Body Foundation Track (docs/32)', field: 'BodyContext.currentWeight, unit', engine: 'generateGoalPlan (safe pace)', plate: 'APM keeps the pace safe, so you never crash-diet.' },
      { id: 'weigh_in', type: 'single', title: 'How often do you want to weigh in?', options: [['weekly', 'Weekly'], ['biweekly', 'Every 2 weeks'], ['none', 'Never, track habits only']], gate: (a, h) => h.any(a, 'weight'), why: 'The app never insists on daily weighing.', bhpc: 'App Body Foundation Track', field: 'BodyContext.weighInCadence', engine: 'supplyDailyActions', plate: 'No daily scale stress.' },
      { id: 'clinician_flag', type: 'single', title: 'Do any of these apply to you right now?', note: 'Pregnancy, diabetes medication, a heart condition, or a history of disordered eating. If yes, or if you would rather not say, APM keeps body steps to habits only until a clinician clears a pace.', options: [['no', 'None of these'], ['yes', 'Yes, one or more'], ['skip', 'Prefer not to say']], essential: true, gate: (a, h) => h.any(a, 'weight'), why: 'Safety stop: yes or prefer-not-to-say pauses pace targets until cleared. Asked even on the quick start.', bhpc: 'I: coaching is not medical advice', field: 'BodyContext.referralActive', engine: 'actionSafetyProblem, referral stop', plate: 'APM keeps you safe without you having to research it.' },
      { id: 'clinician_sup', type: 'yesno', title: 'Is a clinician supervising your plan?', gate: (a, h) => h.any(a, 'weight') && a.clinician_flag === 'yes', why: 'Only supervision allows a faster pace.', bhpc: 'App Body Foundation Track', field: 'BodyContext.clinicianSupervised', engine: 'generateGoalPlan (pace ceiling)', plate: 'The pace limit is handled for you.' },
      { id: 'health_routine', type: 'yesno', title: 'Do you have a daily health routine to remember (vitamins, medication, physio)?', gate: (a, h) => h.bodyOn(a), why: 'A reminder only. APM never stores medication names.', bhpc: 'F: supplements', field: 'healthRoutineReminder (NEW)', engine: 'life-area health routines', plate: 'You stop remembering it. APM reminds you.' },
    ],
  },
  {
    id: 's6', kind: 'questions', name: 'Work & money', intro: 'So APM knows what counts as real work.',
    gate: (a, h) => h.any(a, 'founder', 'operator', 'wealth', 'creator', 'transition'),
    questions: [
      { id: 'income', type: 'multi', title: 'Where does your income come from?', options: [['salary', 'A salary'], ['business', 'My own business'], ['freelance', 'Freelance / consulting'], ['investments', 'Investments'], ['side', 'A side project'], ['none', 'No income right now']], minPick: 1, exclusive: 'none', why: 'Income streams.', bhpc: 'G: income streams', field: 'workMoneyContext.streams[]', engine: 'pillar proposal (wealth/execution)', plate: 'APM keeps each income stream in its lane.' },
      { id: 'income_rank', type: 'rank', title: 'Tap them in order of priority.', options: 'fromIncome', gate: (a) => arr(a, 'income').filter((x) => x !== 'none').length > 1, why: 'Priority order between streams.', bhpc: 'G: priority order', field: 'workMoneyContext.priority[]', engine: 'arbitrateForeground (background order)', plate: 'APM settles the "which first?" question for good.' },
      { id: 'separation', type: 'single', title: 'How should side work fit around primary work?', options: [['after', 'Only after primary work is done'], ['days', 'On fixed days only'], ['none', 'No rule yet; suggest one']], gate: (a) => arr(a, 'income').filter((x) => x !== 'none').length > 1, why: 'Separation of primary vs side projects.', bhpc: 'G: separation of primary work vs side projects', field: 'hardBoundaries[] (+rule)', engine: 'track-rules boundary flags', plate: 'The side project gets its time without the job slipping.' },
      { id: 'real_work', type: 'multi', title: 'What counts as REAL work for you?', options: [['selling', 'Selling / revenue conversations'], ['shipping', 'Shipping the product or deliverable'], ['deep', 'Deep thinking work'], ['hiring', 'Hiring'], ['fundraising', 'Fundraising'], ['clients', 'Client delivery'], ['visible', 'Visible results for my boss'], ['money_moves', 'Money moves (saving, paying down)']], minPick: 1, gate: (a, h) => h.any(a, 'founder', 'operator', 'creator'), why: 'The agenda is built from real work only.', bhpc: 'G: real work vs fake work; VI Invalid agenda clause', field: 'realWork[] (NEW)', engine: 'buildDailyPlan, executableActionProblem', plate: 'Your agenda only contains work that moves the needle.' },
      { id: 'fake_work', type: 'multi', title: 'And what is FAKE work that feels productive?', options: [['inbox', 'Inbox zero'], ['tools', 'Reorganising tools / systems'], ['meetings', 'Meetings with no decision'], ['research', 'Research rabbit holes'], ['social', 'Social media'], ['planning', 'Re-planning']], optional: true, gate: (a, h) => h.any(a, 'founder', 'operator', 'creator'), why: 'Flags busywork in the agenda and in coaching.', bhpc: 'G: fake work; II Law 4', field: 'fakeWork[] (NEW)', engine: 'Operator Discipline track flags', plate: 'APM calls out busywork so you don\'t have to.' },
      { id: 'money_state', type: 'multi', title: 'Which are true today?', options: [['cc_debt', 'I carry credit-card debt'], ['no_buffer', 'Under 1 month of savings'], ['auto_save', 'I save automatically'], ['invest', 'I invest regularly'], ['unknown_spend', 'I\'m not sure what I spend']], optional: true, gate: (a, h) => h.any(a, 'wealth', 'transition'), why: 'Buffer before bets; debt order.', bhpc: 'App Wealth Foundation Track (docs/32)', field: 'wealthContext (NEW)', engine: 'wealth_foundation rules, bufferMet', plate: 'APM puts money moves in the right order for you.' },
      { id: 'equity', type: 'yesno', title: 'Do you own a business or hold equity?', gate: (a, h) => h.any(a, 'founder', 'operator'), why: 'Billionaire High Performance Coach Track only fits ownership games.', bhpc: 'Appendix A Track 1 "When to activate"', field: 'ownership (NEW)', engine: 'recommendTrackKeys (business marker)', plate: 'You only get the filters that fit your game.' },
      { id: 'career_lever', type: 'multi', title: 'What would move you up fastest?', options: [['visibility', 'Visibility with leaders'], ['scope', 'Bigger scope'], ['skills', 'A new skill'], ['sponsor', 'A sponsor'], ['results', 'Measurable results']], optional: true, gate: (a, h) => h.any(a, 'operator'), why: 'Operator persona focus (Career Capital gap).', bhpc: 'docs/32 Operator gap', field: 'careerLevers[] (NEW)', engine: 'Radar career pattern', plate: 'APM keeps your career moves on the calendar.' },
    ],
  },
  {
    id: 's7', kind: 'questions', name: 'Home front', intro: 'Family time gets defended like the biggest meeting of the week.',
    gate: (a, h) => h.any(a, 'parent'),
    questions: [
      { id: 'dependents', type: 'multi', title: 'Who depends on you?', options: [['baby', 'A baby'], ['toddler', 'A toddler'], ['school', 'School-age kids'], ['teen', 'Teens'], ['elder', 'An ageing parent'], ['other', 'Another adult']], minPick: 1, why: 'Shapes family logistics.', bhpc: 'App Home Front Track (docs/32)', field: 'familyContext.dependents[] (NEW)', engine: 'home_front rules', plate: 'APM tracks the family logistics, not you.' },
      { id: 'protected', type: 'multi', title: 'Which family moments are protected?', options: [['school_run', 'School run'], ['dinner', 'Dinner'], ['bedtime', 'Bedtime'], ['weekend_am', 'Weekend mornings'], ['activities', 'Their sports / activities'], ['date', 'Date night']], minPick: 1, why: 'Protected touchpoints are scheduled first.', bhpc: 'App Home Front Track; D red lines', field: 'familyContext.protected[] (NEW)', engine: 'track-rules HOME_TOUCHPOINT', plate: 'These get booked first. Work fits around them.' },
      { id: 'shared', type: 'single', title: 'Who shares the load?', options: [['partner', 'A partner shares it'], ['me', 'Mostly me'], ['coparent', 'A co-parent'], ['help', 'Paid or family help']], why: 'Capacity on hard days.', bhpc: 'E: constraints', field: 'familyContext.shared (NEW)', engine: 'MVD sizing', plate: 'APM sizes your day to the help you actually have.' },
    ],
  },
  {
    id: 's8', kind: 'questions', name: 'Mind', intro: 'APM supplies the prompt, the pages and the plan. You never design a practice.',
    questions: [
      { id: 'practices', type: 'multi', title: 'Which practices matter to you?', options: [['prayer', 'Prayer'], ['meditation', 'Meditation'], ['journaling', 'Journaling'], ['gratitude', 'Gratitude'], ['reading', 'Reading'], ['therapy', 'Therapy sessions'], ['none', 'None right now']], minPick: 1, exclusive: 'none', why: 'Spirit pillar content.', bhpc: 'H: practices', field: 'mindSpiritLearningContext.practices[]', engine: 'pillar proposal (spirit)', plate: 'APM makes room for these without you guarding the time.' },
      { id: 'practice_cadence', type: 'single', title: 'How often?', options: [['daily', 'Daily'], ['few', 'A few times a week'], ['weekly', 'Weekly']], gate: (a) => arr(a, 'practices').length > 0 && !arr(a, 'practices').includes('none'), recommended: () => 'daily', why: 'Cadence.', bhpc: 'H: cadence', field: 'mindSpiritLearningContext.cadence', engine: 'recurrence', plate: 'It repeats on its own.' },
      { id: 'learning', type: 'single', title: 'What do you most want to learn this season?', options: [['leadership', 'Leadership'], ['money', 'Money / investing'], ['health', 'Health'], ['craft', 'A craft or skill'], ['faith', 'Faith'], ['parenting', 'Parenting'], ['none', 'Nothing right now']], why: 'Learning priority.', bhpc: 'H: learning priorities', field: 'mindSpiritLearningContext.learning', engine: 'pillar proposal', plate: 'APM picks the next thing to learn, so you don\'t browse for it.' },
      { id: 'modality', type: 'single', title: 'How do you learn best?', options: [['read', 'Reading'], ['audio', 'Audio'], ['video', 'Video'], ['doing', 'By doing'], ['course', 'A structured course']], gate: (a) => typeof a.learning === 'string' && a.learning !== 'none', why: 'Preferred learning modality.', bhpc: 'H: preferred modality', field: 'mindSpiritLearningContext.modality', engine: 'action wording', plate: 'Learning steps come in the format you\'ll actually use.' },
    ],
  },
  {
    id: 's8b', kind: 'questions', name: 'Spirit', intro: 'One tap. APM writes the daily action for each one.',
    gate: (a, h) => h.pillarOn(a, 'spirit'),
    questions: [
      { id: 'spirit', type: 'multi', title: 'What feeds your spirit?', note: 'Pre-ticked from what you already told us. Faith wording is used only if you pick Faith.', options: [['faith', 'Faith: prayer, scripture, worship, community'], ['meditation', 'Meditation or mindfulness'], ['gratitude', 'Gratitude'], ['nature', 'Nature and stillness'], ['service', 'Service and giving'], ['none', 'Nothing right now']], minPick: 1, exclusive: 'none', prefill: 'spirit', why: 'Spirit pillar content: each choice becomes one generated daily action, a cadence and a floor.', bhpc: 'H: practices (spirit)', field: 'spiritPractices[]', engine: 'generatePractices, pillar proposal (spirit)', plate: 'APM turns each one into one small daily action, with the words written for you.' },
    ],
  },
  {
    id: 's9', kind: 'questions', name: 'Your week', intro: 'Tap days. APM shapes the week around them.',
    after: { id: 'i4', kind: 'week', title: 'Your week is mapped', plate: 'Taken off your plate: fitting it all into the week.' },
    questions: [
      { id: 'heavy', type: 'weekdays', title: 'Which days can be heavy?', options: [['Mon', 'Mon'], ['Tue', 'Tue'], ['Wed', 'Wed'], ['Thu', 'Thu'], ['Fri', 'Fri'], ['Sat', 'Sat'], ['Sun', 'Sun']], optional: true, why: 'Heavy days carry the hardest work.', bhpc: 'I: heavy days', field: 'weeklyCadence.heavyDays[]', engine: 'availability.minutesByWeekday', plate: 'Big tasks land on big days automatically.' },
      { id: 'light', type: 'weekdays', title: 'Which days should be light?', options: [['Mon', 'Mon'], ['Tue', 'Tue'], ['Wed', 'Wed'], ['Thu', 'Thu'], ['Fri', 'Fri'], ['Sat', 'Sat'], ['Sun', 'Sun']], optional: true, why: 'Light days run near MVD scope.', bhpc: 'I: light days', field: 'weeklyCadence.lightDays[]', engine: 'availability.restDays', plate: 'Light days stay light. You won\'t be talked into more.' },
      { id: 'review', type: 'single', title: 'Which day is your weekly review?', options: [['Mon', 'Mon'], ['Tue', 'Tue'], ['Wed', 'Wed'], ['Thu', 'Thu'], ['Fri', 'Fri'], ['Sat', 'Sat'], ['Sun', 'Sun']], recommended: () => 'Sun', why: 'Weekly debrief day.', bhpc: 'I: review day; Prompt #7 weekly debrief', field: 'weeklyCadence.reviewDay', engine: 'weekly review workflow', plate: 'The review shows up on its own, already filled in.' },
      { id: 'recovery', type: 'single', title: 'Do you want a standing recovery day?', options: [['none', 'No'], ['Mon', 'Mon'], ['Tue', 'Tue'], ['Wed', 'Wed'], ['Thu', 'Thu'], ['Fri', 'Fri'], ['Sat', 'Sat'], ['Sun', 'Sun']], recommended: () => 'none', why: 'Planned recovery.', bhpc: 'I: recovery day; Mode 4 Recovery', field: 'weeklyCadence.recoveryDay', engine: 'resolveRuntimeMode (recovery)', plate: 'Rest is scheduled, so it never feels like falling behind.' },
      { id: 'sched', type: 'single', title: 'How should your day be laid out?', options: [['strict_blocks', 'Strict time blocks (9:00 to 10:00)'], ['loose_dayparts', 'Loose: morning / afternoon / evening'], ['ordered_stack', 'Just an ordered list']], recommended: () => 'loose_dayparts', why: 'Agenda format.', bhpc: 'N1: strict blocks vs loose routines vs ordered stack', field: 'schedulingPreference', engine: 'buildDailyPlan format', plate: 'Your day arrives in the shape your brain likes.' },
    ],
  },
  {
    id: 's10', kind: 'questions', name: 'What matters most', intro: 'The big picture, and the lines APM should hold.',
    questions: [
      { id: 'northstar', type: 'single', title: 'What is this all for, long term?', options: [['freedom', 'Financial freedom'], ['lasting', 'Building something that lasts'], ['healthy', 'A healthy body for life'], ['present', 'Being present for my family'], ['top', 'The top of my field'], ['mastery', 'Mastery of a craft'], ['peace', 'Stability and peace']], why: 'North Star filters every later decision.', bhpc: 'B: #1 multi-year outcome', field: 'northStar', engine: 'reveal + Track filters', plate: 'APM keeps the big picture in view, so you don\'t have to.' },
      { id: 'horizon', type: 'single', title: 'Over roughly what horizon?', options: [['1', '1 year'], ['3', '3 years'], ['5', '5 years'], ['10', '10 years']], recommended: () => '3', why: 'Long-horizon thinking (Strategic Patience).', bhpc: 'B: multi-year horizon', field: 'northStarHorizon (NEW)', engine: 'strategic_patience filters', plate: 'APM stops short-term noise from changing the plan.' },
      { id: 'secondary', type: 'multi', title: 'What else needs to stay on track in the background?', options: [['health', 'Health'], ['money', 'Money'], ['business', 'Business / career'], ['relationships', 'Relationships'], ['family', 'Family / home'], ['learning', 'Learning'], ['faith', 'Faith / spirit'], ['identity', 'Confidence / identity']], optional: true, why: 'Background pillars get maintenance, not advancement.', bhpc: 'B: secondary outcomes across health, money, identity, business, relationships, learning', field: 'secondaryGoals[] (NEW)', engine: 'pillar proposal; arbitrateForeground candidates', plate: 'The background is maintained for you. Nothing silently collapses.' },
      { id: 'values', type: 'multi', title: 'Pick up to 5 values APM should protect.', options: [['integrity', 'Integrity'], ['family', 'Family'], ['freedom', 'Freedom'], ['health', 'Health'], ['faith', 'Faith'], ['mastery', 'Mastery'], ['excellence', 'Excellence'], ['service', 'Service'], ['wealth', 'Wealth'], ['peace', 'Peace'], ['courage', 'Courage'], ['loyalty', 'Loyalty']], maxPick: 5, optional: true, why: 'Values filter coaching and arbitration.', bhpc: 'D: core values', field: 'values[]', engine: 'coaching context (Life Graph)', plate: 'APM checks plans against your values for you.' },
      { id: 'lines', type: 'multi', title: 'Which lines should APM hold for you?', note: 'Pre-ticked from what you already told us. Untick anything that is wrong.', options: [['dinner', 'Family dinner'], ['sleep', 'Sleep 7+ hours'], ['sabbath', 'A weekly day of rest'], ['pickup', 'Never miss pickup'], ['no_debt', 'No new debt for wants'], ['workout', 'My workouts'], ['worship', 'Worship'], ['date', 'Date night'], ['no_side_weekdays', 'No side projects on weekdays'], ['no_screens_8', 'No screens after 8 PM'], ['weekends_family', 'Weekends are for family'], ['no_meet_10', 'No meetings before 10'], ['no_work_7', 'No work after 7 PM'], ['phone_bedroom', 'Phone out of the bedroom']], optional: true, prefill: 'lines', why: 'Red lines and hard scheduling boundaries in one list (was two questions).', bhpc: 'D: red lines; N2: hard boundaries', field: 'nonNegotiables[] + hardBoundaries[]', engine: 'track-rules, Radar conflicts, buildDailyPlan, canMiddayReplan', plate: 'APM flags anything that crosses these before it happens. You stop negotiating with yourself.' },
    ],
  },
  {
    id: 's11', kind: 'questions', name: 'How APM coaches you', intro: 'You stay in charge. APM adapts its voice.',
    questions: [
      { id: 'tone', type: 'single', title: 'How hard do you want to be pushed?', options: [['gentle', 'Gentle and supportive'], ['direct', 'Calm and direct'], ['high_pressure', 'High-Pressure Coaching: push me hard when I am stuck or avoiding']], essential: true, prefill: 'tone', recommended: (a, h) => (h.tough(a) ? 'gentle' : 'direct'), why: 'Tone + firmness. Pre-selected to High-Pressure when the Billionaire High Performance Coach Track is suggested; one tap confirms, any option can be picked (BHPC User Authority: never forced).', bhpc: 'K: tone, firmness level; Mode 1 High-Pressure; User Authority', field: 'coachingStyle.firmness', engine: 'coaching state machine slot tone', plate: 'You get the coach you respond to, without asking each time.' },
      { id: 'helps', type: 'multi', title: 'What language helps you?', options: [['short', 'Short and clear'], ['numbers', 'Numbers and data'], ['faith', 'Faith language welcome'], ['sports', 'Sports metaphors'], ['why', 'Remind me why'], ['next', 'Just tell me what\'s next']], optional: true, why: 'Language that helps.', bhpc: 'K: language that helps', field: 'coachingStyle.helps[] (NEW)', engine: 'coaching slot rephrase context', plate: 'Every message is written your way.' },
      { id: 'triggers', type: 'multi', title: 'What language turns you off?', options: [['hustle', 'Hustle talk'], ['guilt', 'Guilt / "you should"'], ['toxic_pos', 'Toxic positivity'], ['swearing', 'Swearing'], ['diet', 'Diet talk'], ['compare', 'Comparing me to others']], optional: true, why: 'Language that triggers is banned in every slot.', bhpc: 'K: language that triggers', field: 'coachingStyle.avoid[] (NEW)', engine: 'coaching slot guard', plate: 'APM never says these to you.' },
      { id: 'start', type: 'single', title: 'How should your day start?', options: [['guided', 'Guided Start: see the whole day, begin with the first step'], ['hard', 'Hard Start: only the first step until I confirm it']], recommended: () => 'guided', why: 'Accountability choice 1.', bhpc: 'L1: Hard Start or Guided Start', field: 'accountability.dayStart', engine: 'Today gating', plate: 'The morning starts itself. No deciding where to begin.' },
      { id: 'scoring', type: 'single', title: 'How should days be scored?', options: [['pillar', 'Hit / Partial / Miss per pillar'], ['showed_up', 'Just "did I show up"'], ['off', 'No scoring']], recommended: () => 'pillar', why: 'Scoring method.', bhpc: 'J: scoring method', field: 'scoringConfig', engine: 'scoreDay', plate: 'APM keeps score so you don\'t replay the day in your head.' },
      { id: 'day_counts', type: 'single', title: 'What makes a day count?', options: [['critical', 'My critical pillars got done'], ['one', 'One meaningful action happened'], ['foreground', 'My #1 goal moved']], gate: (a) => a.scoring !== 'off', recommended: () => 'critical', why: 'Day verdict rule.', bhpc: 'J: what makes a day count', field: 'scoringConfig.dayCounts (NEW)', engine: 'scoreDay verdict', plate: 'The finish line is set in advance. No moving goalposts.' },
      { id: 'floors', type: 'multi', title: 'On a 2-out-of-10 day, what is the smallest thing that still counts?', options: 'floorOptions', minPick: 1, maxPick: 3, essential: true, prefill: 'floors', why: 'Minimum floors for the MVD.', bhpc: 'L3: minimum floors; II Law 6 MVD', field: 'minimumFloors{pillar}', engine: 'selectMinimumViableAction, generateGoalPlan (userFloorMvd)', plate: 'Bad days already have a plan. One small thing, then rest.' },
      { id: 'reminder', type: 'yesno', title: 'Nudge me if I go 7 days without coaching?', why: 'Coaching reminder; never blocks execution.', bhpc: 'L4: coaching reminder', field: 'accountability.coachingReminderAfterDays', engine: 'push evaluation', plate: 'You never have to remember to check in.' },
    ],
  },
  {
    id: 's12', kind: 'questions', name: 'Your morning launch', intro: 'Up to 5 physical steps that start the day for you.',
    after: { id: 'i5', kind: 'morning', title: 'Your Morning Sequence', plate: 'Taken off your plate: how to start the day.' },
    questions: [
      { id: 'bed', type: 'single', title: 'Is getting out of bed hard for you?', options: [['yes', 'Yes'], ['sometimes', 'Sometimes'], ['no', 'No']], essential: true, why: 'Yes or Sometimes adds a ready-made 10-minute Pilates-style mobility routine done in bed as step 1 of the morning (owner, 7 Oct 2026).', bhpc: 'M1 + M2 (in-bed movement)', field: 'morningSequence (design input)', engine: 'normalizeMorningSequence', plate: 'You don\'t design a routine or argue with yourself about getting up. The first 10 minutes happen lying down.' },
      { id: 'launch', type: 'single', title: 'Pick your morning launch.', options: [['quick', 'Quick: glass of water, then my first task'], ['calm', 'Calm: feet down, 1 minute of breathing, water, first task'], ['faith', 'Faith: 1 minute of prayer, water, first task'], ['custom', 'Build my own (5 quick taps)']], recommended: () => 'calm', why: 'Three ready-made BHPC Morning Sequences; M1 to M5 only for people who want to design their own.', bhpc: 'M1 to M5 (preset); IV Step 5D', field: 'morningSequence[≤5]', engine: 'normalizeMorningSequence', plate: 'Your first minutes are designed for you. No thinking at 6 AM.' },
      { id: 'bed_move', type: 'single', title: 'Would 30 to 60 seconds of movement in bed help? Pick one.', options: [['none', 'No thanks'], ['shoulder_rolls', 'Shoulder rolls'], ['leg_raises', 'Leg raises'], ['twists', 'Seated twists'], ['feet_floor', 'Feet to the floor']], gate: (a) => a.launch === 'custom' && a.bed === 'no', why: 'In-bed wake-up movement.', bhpc: 'M2', field: 'morningSequence[step]', engine: 'normalizeMorningSequence', plate: 'Your body gets moving before your brain argues.' },
      { id: 'mental', type: 'single', title: 'How do you want to start mentally?', options: [['silence', 'Silence'], ['breathing', 'Breathing'], ['gratitude', 'Gratitude'], ['prayer', 'Prayer'], ['visualization', 'Visualisation']], gate: (a) => a.launch === 'custom', why: 'Mental start.', bhpc: 'M3', field: 'morningSequence[step]', engine: 'normalizeMorningSequence', plate: 'Your mind has one job for one minute.' },
      { id: 'where', type: 'single', title: 'Where should that happen?', options: [['bed', 'In bed'], ['sitting', 'Sitting up'], ['standing', 'After standing']], gate: (a) => a.launch === 'custom', why: 'Placement in sequence.', bhpc: 'M4', field: 'morningSequence order', engine: 'normalizeMorningSequence', plate: 'The order is set. No thinking at 6 AM.' },
      { id: 'start_action', type: 'single', title: 'What makes the day feel officially started?', options: [['water', 'Drink water'], ['sunlight', 'Sunlight'], ['coffee', 'Coffee'], ['laptop', 'Open the laptop'], ['outside', 'Step outside'], ['journal', 'One-line journal']], gate: (a) => a.launch === 'custom', why: 'The physical start signal.', bhpc: 'M5', field: 'morningSequence[last]', engine: 'normalizeMorningSequence (max 5)', plate: 'One action flips the switch. APM reminds you which.' },
      { id: 'trigger', type: 'single', title: 'When should your agenda arrive?', options: [['wake', 'The moment I wake up'], ['wake15', '15 minutes after I wake'], ['wake30', '30 minutes after I wake']], recommended: () => 'wake15', why: 'Automated morning trigger (never rely on memory).', bhpc: 'IV Step 5D: automate the morning trigger', field: 'morningTriggerTime (NEW) + push permission', engine: 'push registration/evaluation', plate: 'You never ask for your agenda again. It comes to you.' },
    ],
  },
  {
    id: 's13', kind: 'questions', name: 'Anything else', intro: 'The only typing in the whole setup, and it\'s optional.',
    questions: [
      { id: 'catchall', type: 'text', title: 'Anything else on your mind? Dump it here.', optional: true, why: 'Catch-all: anything a closed question missed.', bhpc: 'Prompt #1 "specific concerns or constraints" after each category', field: 'catchAll (NEW, untrusted text)', engine: 'intake_profile_synthesis (LLM, via Privacy Gateway)', plate: 'Whatever you type here, APM sorts. You don\'t have to organise it.' },
    ],
  },
];
